### ISSUE TITLE
The demo page is a 404 error

### ISSUE THREAD

**Issue by laheadle** [pepe/showrum#35]
https://pepe.github.io/showrum/

**Comment by pepe** [comment]
Thank you for the head up. I will actually using it in two weeks, as I will be teaching, so I will repair/upgrade it.

**Comment by laheadle** [comment]
Beautiful piece of code btw. Very convincing.

**Comment by pepe** [comment]
Wow. Thank you sir! You made my morning. 

ASAP I will move it to shadow-cljs build, and fix the demo.

**Comment by pepe** [comment]
So as sometimes is the case, the real problem with the demo was bad link as I moved the repo from my personal GH account to company one. Nevertheless it made me move it to shadow-cljs and create the new build, and change the README finally. 

Still thank you very much for head up.
